spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/petclinic
    username: petclinic
    password: petclinic
  sql:
    init:
      mode: always
      platform: postgres
